[package]
name = "chromifer-integration"
description = "Build and execute generated Chromifer bridges through GN and Ninja"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
chromifer-build = { path = "../chromifer-build" }
chromifer-cabi = { path = "../chromifer-cabi" }
chromifer-manifest = { path = "../chromifer-manifest" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
