// Generated by Chromifer from an explicit C ABI contract.
// Do not edit manually.

#ifndef CHROMIFER_C_ABI_EXAMPLE_H_
#define CHROMIFER_C_ABI_EXAMPLE_H_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

int32_t chromifer_add(int32_t left, int32_t right);
bool chromifer_buffer_is_valid(const uint8_t* data, uintptr_t length);

#ifdef __cplusplus
}  // extern "C"
#endif

#endif  // CHROMIFER_C_ABI_EXAMPLE_H_
